### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by andresmanelli** [wekan/wekan#2209]
This issue is a follow-up of #2165 

## TODO
- [ ] Add fix for #1959 
- [ ] Create template from element
- [ ] Make sure the original issue TODO list is OK

### TODO->next()
- [ ] Templated users

@rterwedo @xet7 If I forgot something, please comment below.

**Comment by xet7** [comment]
@andresmanelli 

Please test Wekan meteor-1.8 branch why it gives this error? That branch has meteor 1.8.0.2 and I used rebuild-wekan.sh without cloning repo repo https://github.com/meteor-useraccounts/core.git to wekan/packages/ directory.
```
Exception in template helper: TypeError: Cannot read property 'getTemplatesBoardSlug' of undefined

**Comment by xet7** [comment]
Currently there is problems that templates board disappeared. There should be:

- [ ] ability to manage template boards same way like other boards, adding and removing template boards
- [ ] selecting users that use have these template boards
- [ ] are templates visible to users
- [ ] are templates modifiable for that template users or not

**Comment by xet7** [comment]
@andresmanelli 

After some bug did make my templates board disappear, there needs to be addes feature/fix, that every time when starting Wekan there should be check is there templates board, and if not, create it.

**Comment by MelBourbon** [comment]
> * [ ]  Create template from element

Could be achieved by allowing to copy a card to the template board. At least on card level.

**Comment by Jacobclaerhout** [comment]
@andresmanelli it seems as if importing "board templates" is not functioning properly.

In Terms of UX it is also strange that users are asked twice to name their new Board/List/Card, yet that only the last entry counts.

**Comment by Jacobclaerhout** [comment]
The main value of templates is being able to share them as an admin towards team members. Is that related with what you mean with templated users, @andresmanelli?

**Comment by andresmanelli** [comment]
I think the original idea was to have user templates (create a new user with a set of default boards, etc)

Sharing templates would be great, but for the moment that is not covered.

**Comment by neurolabs** [comment]
#2310 might be a collateral of the new templates feature

**Comment by sfahrenholz** [comment]
the "default swimlane" Template is missing. If the Swimlane "Swimlane Templates" manual adding, it works fine.

**Comment by gitzimo** [comment]
Hello all! First of all: Great work, I love WEKAN and it improved our work quite a lot!
But are there any news on this topic? We're using v3.63 and I didn't find anything in the changelog concerning fixes for templates. I don't quite understand the difference between "All Boards - Templates" and "User - Templates" and I do not find it explained in the doc. I can invite some user to "my" template board and he is seeing the templates. But when I make a new board and invite him to that board he doesn't see the card templates when adding cards. Does everyone have his/her "own" templates? Thanks in advance for shedding some light on this!, Regards, Thomas

**Comment by xet7** [comment]
@gitzimo 

I added info to [Templates wiki page](https://github.com/wekan/wekan/wiki/Templates).

**Comment by gitzimo** [comment]
Thanks a lot!

**Comment by vjrj** [comment]
Using `3.70.0` I have a Page not found pressing in "All Boards > Templates". Any error log in the js console. I have a older wekan (`2.75`) and this Template section works. 

Is this normal because this is a work in progress? TIA!

**Comment by xet7** [comment]
@vjrj 

Please add error log as comment to this issue, if you have errors.

**Comment by xet7** [comment]
@vjrj 

Are you using password login, or something other like LDAP/OAuth2 ?

**Comment by vjrj** [comment]
I don't see any error in the server or client :-/ and I'm using password login in both servers.

**Comment by Keelan** [comment]
> The main value of templates is being able to share them as an admin towards team members.

+1.
I would love to be able to create board card specific templates. 
Every one on that board who has permission to create cards can use any of the board card templates.
