### ISSUE TITLE
GitLab integration with Wekan Rules Sync

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#2698]
Moved to here from [#109](https://github.com/wekan/wekan/issues/109#issuecomment-530454366) as requested by GitLab integration Sponsor @gotjoshua . Currently @xet7 working on this issue, as first step here is Roadmap combined by @xet7 .

## Wekan Sync to GitLab and back
- [ ] Linking issues to the external service for #number syntax, like [Pretty ID](#2450) and [Board Key](#2449)
- [ ] Is repo push mirroring already in GitLab CE? See [1](https://gitlab.com/gitlab-com/www-gitlab-com/merge_requests/11316) - [2](https://gitlab.com/gitlab-org/gitlab-ce/issues/18732) - [3](https://gitlab.com/gitlab-org/gitlab-ce/issues/42099). Related [CI/CD to GitHub and Kubernetes](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/) and [HN](https://news.ycombinator.com/item?id=16649678). [CI/CD to external repos not open yet maybe](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#gitlab-cicd-for-external-repos) ?
- [ ] Sync issues between Wekan and GitLab with Wekan Rules and [SyncedCron timing](https://github.com/wekan/wekan/pull/2555), like with [Gogs](https://github.com/wekan/wekan-gogs)
- [ ] Sync comments
- [ ] Sync activities
- [ ] Sync attachments
- [ ] Post-actions to sync with Wekan Rules like group/private [Push notifications, and notification settings](#2026). What is [LINE messenger](https://github.com/wekan/wekan/issues/109#issuecomment-126780056) ?
- [ ] Embed Wekan to GitLab, GitLab to Wekan, with iframe
- [ ] GitLab as OAuth2 provider to Wekan, maybe already works
- [ ] Some ideas from related [GitLab issue boards](https://gitlab.com/gitlab-org/gitlab-ce/issues/17907)

## About GitLab

- There is GitLab interview at [FLOSS Weekly](https://twit.tv/shows/floss-weekly/episodes/473?autostart=false), and from that xet7 got info that not all features are in Open Source version. For example, when xet7 tried to enable syncing latest Wekan changes from GitHub to GitLab.com, there was text that it is paid only / Enterprise feature. There seemed to be some translation support in GitLab, but no Finnish translation yet.
- [External CI/CD configuration in Starter and Bronze](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#external-cicd-configuration-in-starter-and-bronze) "Note that as part of our commitment to open source, public projects on Free GitLab.com have features equivalent to a Gold level subscription. So those public projects will continue to have this feature." so if I setup CI/CD at GitLab.com for Wekan Open Source project, I presume it stays working, and I can look at all features at Gold level that should work now at GitLab.com
- [Navigate to external issue tracker](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#navigate-to-external-issue-tracker), could this be used to replace GitLab issues/board with Wekan board
- [SAST security report on pipelines view](https://about.gitlab.com/2018/03/22/gitlab-10-6-released/#sast-security-report-on-pipelines-view) This would be nice, previously xet7 has already got security reports from quay.io

## Related: What else to sync with Wekan Rules
- [ ] Jira
- [ ] Trello
- [ ] GitHub Projects and issues
- [ ] Sending to REST API
- [ ] Receiving Webhook

## Related: Other Wekan platforms
- [ ] Friend: automate other Friend apps
- [ ] Univention: automate NextCloud etc
- [ ]  Sandstorm: automate other Sandstorm apps

**Comment by gotjoshua** [comment]
Nice start @xet7 !  
Here is my personal priority list:

1. linking to an external issue and displaying specific parts of the issue within the Wekan Card 
   - I don't think any CI/CD would be needed for that as Wekan could simply poll the api.
2. Allowing the issue to be edited from within the Wekan card 
LeanLabs did many things VERY nicely in terms of UI eg:
   - Quick adding of tasks
   - Labels
   - Milestones
   - Swimlanes

I started a wekan board on the demo site:
https://wekan.indie.host/b/q94r7uguevibEKX29/wekan-gitlab-integration

**Comment by xet7** [comment]
@gotjoshua 

Please move your demo site to https://boards.wekan.team and invite me there instead and add BoardAdmin access to me, because there is newest Wekan.

That https://wekan.indie.host is running old version of Wekan, and sometimes is not online.

**Comment by xet7** [comment]
@gotjoshua 

About your personal priority list, can you add to this issue screenshots or animated gifs to this issue (or link to them elsewhere) about LeanLabs UI, so I can see how that UI is different from Wekan. Wekan also has Cards (Tasks), Labels, Swimlanes (click top bar switch button Lists/Swimlanes/Calendar).

**Comment by gotjoshua** [comment]
Both [Gitlab Boards](https://gitlab.com/gitlab-org/gitlab-ce/issues/17907#moving-issues) and lean labs are using labels to indicate which "list" the card belongs in.
This seems great for visibility when viewing the issue in gitlab, but it requires that only one of the list labels are applied to a given issue (or at least that the board knows which to choose to place the issue - eg default to leftmost or rightmost)

**Comment by xet7** [comment]
Yes, leanlabs is data-driven and Wekan is not yet, because data is not yet synced to Wekan.

Wekan has roles like CommentOnly, where only comments are editable. So similar role can be added if something does not need to be editable.

Wekan also has board Outgoing Webhooks, so board changes could be sent to GitLab with it, if there is some way at GitLab to receive it, or that way could be added to Wekan.

**Comment by xet7** [comment]
@gotjoshua 

Please add GitLab API docs URLs to:
https://boards.wekan.team/b/7mPjujLn25K5hTDG4/wekan-gitlab-integration

I'm just a newbie on both LeanLabs and GitLab. I know only Wekan.

**Comment by xet7** [comment]
Well, after failing to build and update LeanLabs kanban, I wrote [this blogpost](https://blog.wekan.team/2019/09/illusion-of-differences-between-operating-systems-programming-languages-and-web-frameworks/index.html).

**Comment by gotjoshua** [comment]
Well, yeah staying agnostic is the key to enlightenment ; -)
... and productivity for that matter.

I think it will be best to use a library such as:
https://www.npmjs.com/package/gitlab
has links to both the official docs and [mentions the libraries "goodies"](https://www.npmjs.com/package/gitlab#docs)

**Comment by gotjoshua** [comment]
Hello again after a long silence...
@xet7, Have you looked into gitlab integration any more?
Did you see my links to the gitlab api docs on those cards in the wekan team board?
  - is that what you meant?

**Comment by xet7** [comment]
@gotjoshua 

1. Please add screenshots [to this card](https://boards.wekan.team/b/7mPjujLn25K5hTDG4/wekan-gitlab-integration/9LtYwDuRGSSWRZwGi) of data at GitLab, the same data that should be also visible at Wekan.

2. Then please add to [GitLab Integration board](https://boards.wekan.team/b/7mPjujLn25K5hTDG4/wekan-gitlab-integration) more lists etc to mockup how GitLab data should be visible in Wekan.

This way I will get better idea about what I should do.

**Comment by miff2000** [comment]
> Well, after failing to build and update LeanLabs kanban, I wrote [this blogpost](https://blog.wekan.team/2019/09/illusion-of-differences-between-operating-systems-programming-languages-and-web-frameworks/index.html).

I'm keen to see this integration too. I also have a working `docker-compose.yml` file for LeanLabs KanBan if that will help?

Are there any other bits I can help with to push this forward?

**Comment by xet7** [comment]
@miff2000 

Please add your working `docker-compose.yml` as comment to this issue. Thanks!

Problem with LeanLabs KanBan was, that I could not get newest repo version to compile. Maybe some previous release tag would work. I did make modifications to source code paths to point to my forker repo at my newly created GitHub org:
https://github.com/kanlab/kanlab

From what I tested the installed version that @gotjoshua provided login to, LeanLabs kanban is very basic, minimal amount of features, and many bugs that do not exist in Wekan at all.

LeanLabs kanban has the advantage that it is written in Go, so it uses much less RAM memory and disk space, and I presume it's one executeable binary, that is easy to crosscompile to multiple platforms. Compiling Go is very fast. I have programmed with Go, with the experience that Go binaries do crash very easily, I have not learned how to do error handling in Go properly.

Wekan currently has about 30 000 Javascript files. When I try to unzip Wekan bundle on ReactOS, filesystem crashes, ReactOS can not handle that much files. Building Wekan is slow, so I use fast server that has NVME disk.

I will continue doing GitLab integration. Problem is I made a mistake, I accepted more paid work to my todo list. And it's just me coding all those features, on my todo list. I do know how to code all these features, but problem is that it takes some time to code all those features. I can not promise that all those features will be ready immediately.

**Comment by magick93** [comment]
@xet7 - thanks, your efforts are really appreciated.

I think there would be a lot of interest in this bidirectional issue syncing with gitlab.

Im a bit rusty with javascript but am happy to help.

**Comment by magick93** [comment]
And regarding https://boards.wekan.team/b/7mPjujLn25K5hTDG4/wekan-gitlab-integration/nayBBMDqZ7sK39bFk - May I suggest that, rather than board-to-project mapping, that you have a board that can import selected issues from any gitlab project that the user has access to.

The reasons for this are:

- A gitlab project already comes with a board. But to have a board that allows a kanban view of many projects requires the EE license. If Wekan can have a board that can show issues from many projects would be a point of difference from Gitlab CE.
 - Ultimately it would be good if Wekan can have a board that pull in, and sync, with many other issue trackers.

**Comment by gotjoshua** [comment]
> ... that can import selected issues from any gitlab project that the user has access to ...

I agree, and still I would also love to have flexible swimlane options.


the great thing about project to board mapping is that you can rearrange by assignee, author, priority, milestone, labels etc into swim lanes

maybe it could be cool to have special dynamic swimlanes that would move cards vertically based on those parameters (but of course maintain their horizontal "list" position).

>would be a point of difference from Gitlab CE.

Wekan is already worlds apart from the primitive GitLab board... 

Another thought about the project-to-board vs individual issue-to-card syncing:
- Ideally, it would be great to have both options
- If we only had project-to-board, one could make a meta board and use Wekan card links to add cards from the "project board" to the "meta board"

**Comment by xet7** [comment]
> The reasons for this are:
> 
>     * A gitlab project already comes with a board. But to have a board that allows a kanban view of many projects requires the EE license. If Wekan can have a board that can show issues from many projects would be a point of difference from Gitlab CE.

But is that evil ? Am I destroying business models of GitLab, Trello and Jira ?

**Comment by xet7** [comment]
Hmm, I think I am not anywhere close of destroying GitLab/Trello/Jira, they still have a lot of customers.

**Comment by miff2000** [comment]
> Please add your working `docker-compose.yml` as comment to this issue. Thanks!

Here you go. Taken from https://gitlab.com/whirm/kanban/blob/master/docker-compose.yml. All I needed to do was clone the repo and run `docker-compose up`.

To set the OAuth side working, you need to use a GitLab account (sign-up is free), then create an Application, and you'll get the given the `KANBAN_GITLAB_CLIENT` and `KANBAN_GITLAB_SECRET` below.

````yaml
proxy:
  image: leanlabs/nginx:1.0.1
  volumes:
    - "./build/conf.d:/etc/nginx/conf.d"
    - "./build/certs:/etc/nginx/certs"
    - "./build/sites-enabled:/etc/nginx/sites-enabled"
  links:
    - kanban:kanban
  ports:
    - "443:443"
    - "80:80"

kanban:
  image: leanlabs/kanban:1.7.2
  environment:
    # URL on which Leanlabs Kanban will be reachable
    - KANBAN_SERVER_HOSTNAME=http://kanban.192.168.10.5.xip.io
    # This string is used to generate user auth tokens
    - KANBAN_SECURITY_SECRET=ukfast2019
    # Your GitLab host URL
    - KANBAN_GITLAB_URL=https://gitlab.devops.ukfast.co.uk
    # Your GitLab OAuth client ID
    - KANBAN_GITLAB_CLIENT=f9ad3039c4e3d9f614704988b7d6ad28c0af978642a28ec68a7313b7293892d9
    # Your GitLab OAuth client secret key
    - KANBAN_GITLAB_SECRET=19498ae2298002d1b78a898246f761463ac874f91b37195d757620dff5eeef38
    # Wheter to enable sign up with user API token
    - KANBAN_ENABLE_SIGNUP=true
    # Redis server address - IP:PORT
    - KANBAN_REDIS_ADDR=redis:6379
  links:
    - redis:redis
  command: ./kanban server

redis:
  image: leanlabs/redis:1.0.0
  volumes:
    - "/data:/data"
```

**Comment by gotjoshua** [comment]
not sure if its a great idea to post your client ID and secret publicly...

I usually also don't include them in my docker-compose, but rather as VARs in a .env file

**Comment by CandleHater** [comment]
I'd like to also contribute 50 € now and 50 € after finishing this feature. Please contact me in case this is still being worked on.

**Comment by xet7** [comment]
@CandleHater 

For this feature, originally only 50 € has been paid by @gotjoshua and I have already spent that time during starting of development of this feature. So this feature is currently waiting for when somebody can [sponsor continuing development of this feature](https://wekan.team/commercial-support/).

**Comment by tobiasgraeber** [comment]
Hi @xet7 ,

regarding the "sponsor continuing development of this feature"-link (
https://wekan.team/commercial-support/) you posted above:

Can you please give some more Details? To me it is not clear what´s exactly needed here to proceed with the development of this feature. 

I mean....yes the further development depends on somebody to support it by a payment but the question is, how much money do you need to complete this full feature "Wekan Sync to GitLab and back" as stated in post 1?

The Select Box below point 4 on this page ("Feature or Fix Size") hase several select options.

Which option would be necessary / How high are the costs?

Thanks in advance!

**Comment by xet7** [comment]
@tobiasgraeber 

Option Medium 500 euro. With that, I plan to get some kind of sync working. After that, we can look is it enough, or is some more advanced required.

**Comment by Techsigns** [comment]
@xet7 what is option medium? And how long would it take to finish full integration? I'm really interrested and would like to contribute, too

**Comment by xet7** [comment]
@Techsigns 

At https://wekan.team/commercial-support/ is various payment options at PayPal dropdown, and those have some names and amounts, although with TransferWise there would be less fees and it would work faster.

When there is multiple people interested in feature, and each would contribute for example 50 euro, the that would allow this to continue. Previous first 50 euro has been already used in beginning to try to figure out how to develop this. Nobody has yet contributed anything to allow this to continue.

In general, coding a feature goes like this, for example:
1. I look at what is required, APIs and Wekan code where this would fit, what kind of UI would work best.
2. I write some small amount of code to test does this work.
3. I add that code to Wekan and check does it work or break Wekan.
4. If it breaks Wekan, think about different design, and go back to step 2.
5. Get first basic sync feature working, for example syncing one card, manually with button.
6. Look how to make possible syncing card with some schedule, like existing cron functionality, or external cron like Sandstorm cron.
7. Look what it would take to sync more cards etc at once.
8. Look could this sync feature be generalized in some way to Rules wizard, that it would be possible to sync with any API. Or alternatively, write info to wiki how to add some new API to Wekan with pull request.

Well, how long it would take, yes I would also like to know. I would also like to know beforehand some lottery numbers. Programming is like looking a way in labyrinth in what way it could be made working, and sometime finishing. But first I would need some amount of contributions to be allowed to continue.

**Comment by immanuelfodor** [comment]
Hi Everyone, I've just found this issue about Gitlab-Wekan syncing, but I've found no reference to a one-time migration, like moving all issues to Wekan from Gitlab, and then using Wekan only from that point. Does Wekan supports this, or is there any plugin/extension/workaround to achieve this when both tools are self-hosted? Apart from a tedious copypaste session :D

**Comment by xet7** [comment]
Hi @immanuelfodor :)

Well, this issue [got paused in Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/6fjTaDWXT5jJken2u). At beginning this issue had 50 euro funding. I did spend much more time than that at starting implementing this. After that, many promised to [participate in funding this](https://wekan.team/commercial-support/), but no-one did. I don't know why. Did they not want this feature?

Anyway, about workarounds:
- Wekan-Gogs integration: https://github.com/wekan/wekan-gogs
- Git-Bug bridge, I have not tested it yet https://github.com/MichaelMure/git-bug
- [Wekan API example](https://github.com/wekan/wekan/wiki/New-card-with-Python3-and-REST-API)

I don't know do those help. There is not yet integrated import feature. It is the purpose of this feature to implement import/sync with GitLab.

**Comment by immanuelfodor** [comment]
Thanks for the quick reply! Maybe it's solvable in an intermediate Gogs or git-bug instance but it would be so great to have an e.g. Python script that connects to a Gitlab with an access token, takes all issues from a repo, then recreates them on a Wekan board. Without UI or web integration, just a utility script as MVP with simple constants as input. Should I create a separate issue for that?

**Comment by xet7** [comment]
@immanuelfodor 

You can add your script in .zip archive as attachment to comment in this issue.

Another possibility is create Wekan board, export it to Wekan JSON, and export or save GitLab board, and convert to Wekan board JSON, and at all boards page `New Board / Import / From previous export`.

Some example code is also at CSV/Excel issue #395 that also is not in Wekan yet.

**Comment by immanuelfodor** [comment]
Interesting idea, but looks doable. 

There are various options to export Gitlab issues to CSV, after a quick search:
- Perl: https://gitlab.com/emobix/get-all-gitlab-issues-as-csv
- Python: https://collaborating.tuhh.de/hos/modernes-publizieren/offen/software/middleware/gitlab-exporter#pi-project-issues

AFAIK `jq` can parse CSV files then transform the data and output JSON, maybe it could be done in a long bash one-liner.

I do not have a Wekan board yet to check the exported format, is there somewhere an example how it's structured? I've really just found this project :)

**Comment by xet7** [comment]
You should install Wekan, first registered user is admin and can export. https://wekan.github.io
