### ISSUE TITLE
Feature Request: UI improvements (paid)

### ISSUE THREAD

**Issue by jeroenstoker** [wekan/wekan#3086]
## Add custom CSS file from URL.

**Server Setup Information**:
* The current version with snap
Wekan Versie	4.01.0
Meteor versie	1.10.2
Node versie	12.16.3
MongoDB versie	3.2.22
MongoDB storage engine	wiredTiger

**Problem description**:
I am sharing my boards with clients. It works great but there are some design small design issues that bother me as designer. **I would like to pay** for an option to make it possible to include a custom CSS file from a given URL. Not a theme, but CSS to have some more space and a cleaner layout. Also it can help me to add our branding.

I would like to be able to enter a URL, for example:
https://domain.com/custom.css that will be applied in the and of all the layouts. So if this URL is there it should be loaded to the end of each document.

I think it should be in Admin Panel > Settings > Layout > Load custom CSS.Just a text input field would be great. Otherwise, a textarea with custom CSS would also be great.

For now I have added styles in to the Stylish Plugin, but my customers can of course not see it. The example of the CSS I would like to load is this. Please remind this is just a quick and dirty version, but this makes a lot more possible for me.

```
/* General */
body {background:#f5f5f5;}

#header-quick-access 					{padding:10px; font-size:14px; background: #333 !important;}
#header-quick-access ul 			    {overflow:visible;}
#header-quick-access ul li.current 		{border:0 !important; font-weight:bold;}
#header-quick-access ul li.separator 	{display:none;}
#header-quick-access ul li:nth-child(3) {margin-right:30px;}
#header-quick-access ul li a 			{padding:5px 10px; border-radius:2px;}
#header-quick-access ul li.current a 	{border-radius:2px; background:rgba(255,255,255,.2);}
#header #header-main-bar h1             {font-family:"Poppins"; font-weight:bold;}

.swimlane {background:#f5f5f5;}

/* All board views */
.board-list .board-list-item            {padding:20px;}
.board-list-item-name                   {font-family:"Poppins"}


/* Board */
.list 	{background:transparent; border-left:0; margin:10px 0; padding:0px;  border-radius:5px; min-width:300px}
.list:first-child                           {margin-left:20px;}
.list.list-composer.js-list-composer 	    {opacity:.1; transition: all .3s ease; min-width:80px}
.list.list-composer.js-list-composer:hover 	{opacity:1}

.list-header 					            {background:none; border-bottom-width:0px;} 
.list-header .list-header-name 	            {font-family:"Poppins"; color:#000; font-weight:500;}


/* Card changes */
.minicard 						            {background: #FFF; padding: 15px 15px 10px; box-shadow: 0 3px 8px rgba(0,0,0,.05);}
.minicard-title 				            {line-height: 1.5em;}
.minicard .minicard-cover 		            {background-size:cover; margin: -15px -15px 10px; height:100px}

.card-label-orange 				            {color:#fff;}
.card-date 						            {font-size:12px; padding:3px 5px;}

/* Illegal changes */
.card-details-item-received,
.card-details-item-start,
.card-details-item-end,
.card-details-item-assignees,
.card-details-item-name  	      {display:none !important;}
.card-details-item-received  	  {display:none !important;}
/* End illegal changes */


/* Pop over */
.pop-over {box-shadow: 0 4px 20px rgba(0,0,0,.1); border:0; border-radius:5px;}
.pop-over .header 				      {padding:10px; border-bottom:0; border-radius: 5px 5px 0 0; background:#eee;}
.pop-over .header .header-title       {font-family:"Poppins"; font-size:16px; color:#333;}
.pop-over .header .close-btn          {display:none;}
.pop-over .content-container .content {padding: 5px 20px 20px;  width: 260px;}
.pop-over-list li > a                 {border-radius:5px;}
.pop-over-list li > a > i             {margin-right:5px;}
.pop-over-list li>a .sub-name         {margin-bottom:8px;}



/* Sidebar */
.sidebar .sidebar-shadow  {box-shadow: 0 0 60px rgba(0,0,0,.2)}
.sidebar .sidebar-content {padding:30px;}

```

![Schermafbeelding 2020-05-12 om 23 10 27](https://user-images.githubusercontent.com/2196007/81746216-5cc33380-94a6-11ea-9fc1-8e3614913b79.jpg)
![Schermafbeelding 2020-05-12 om 23 11 02](https://user-images.githubusercontent.com/2196007/81746163-46b57300-94a6-11ea-9980-b0b6cde21bad.jpg)
![Schermafbeelding 2020-05-12 om 23 10 44](https://user-images.githubusercontent.com/2196007/81746195-50d77180-94a6-11ea-9634-5a5485ab3a88.jpg)

**Comment by ikwilzitzakken** [comment]
Ah this would be great. I am also using snapcraft, and this way I can add my custom css that will last in the future. Will donate €50

**Comment by xet7** [comment]
I don't know yet would it be safe to allow custom CSS:
https://security.stackexchange.com/questions/24163/how-dangerous-is-it-to-use-css-styles-from-an-untrusted-source

**Comment by xet7** [comment]
Also, custom CSS can very easily break Wekan.

**Comment by xet7** [comment]
Doh, you already paid. Ok I'll try to figure it out.

**Comment by jeroenstoker** [comment]
Wel paid... its a small donation to be honest. I know that CSS can break it, but I think you just have to know what you are doing, also when adding CSS.

It doesn't need to be an external file. It can also be a textarea that will be just included at the bottom of the DOM for example. You'd make me very happy. Thank you a lot.

**Comment by Khasem** [comment]
Great idea! This would be very useful. It would make it also complete.

**Comment by xet7** [comment]
I had to previously find a way [how to fix Custom Javascript in RocketChat](https://forums.rocket.chat/t/big-issue-with-custom-javascript/261/4?u=xet7) because it broke my RocketChat install.

Also, previously I had to [fix XSS bug](https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v385-2020-03-23-wekan-release) because adding Javascript to input fields did run that Javascript code.

I'll try to find is there a safe way to do this.

**Comment by jeroenstoker** [comment]
Hm... I think that when you just load a given URL, that the admin can add in the layout settings it would be fine. People that use css a lot can probably host a css file themself right?  
By the way, CSS is not javascript, which is more dangerous then css I guess. I'll be patient! (I also told some friends about this).

**Comment by xet7** [comment]
Current paid amount is visible [at Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license/JxrT6fkxdGcBLcp6o). Others interested in this [can also participate](https://wekan.team/commercial-support/). Most likely this requires more thinking and coding that current amount.

There could maybe be settings for font sizes, colors etc, changing those would be more safe that full CSS that can break layout.

For those `illegal changes`, there already is `Board Settings / Card Settings` where those fields can be hidden from card.

**Comment by xet7** [comment]
Any custom CSS could just hide all of Wekan UI and if there are many users it's disruption for everyone. So adding some specific settings would be much safer.

**Comment by xet7** [comment]
From @jeroenstoker 

> Also it can help me to add our branding.

Question from @xet7 

What kind of branding? Related #1493

**Comment by jeroenstoker** [comment]
I’m not sure if it is clear. The CSS I would like to add should be for everybody that uses our instance the system. Just like the mail settings which are also system wide.

We are a web design company and we care a lot about branding and small details. I would like to modify things like this (for now):
- Removing the x (close) buttons where it is absolute
- change the fonts and titles of the tiles
- changes line height
- change the border radius of elements the adjust it to our branding
- change the background to add waves
- maybe add a small logo of icon on certain places
- change icons to different once’s that we use in other documentation
- icon sizes in the mobile version
Etc.

These are all possible when I just load a custom CSS file that I provide myself. These settings won’t be overwritten when automatically updating to a newer version. Of course they need to be reviewed then. Also with this option it would not be needed the make a ton of extra settings but I can do these small changes myself.

In my opinion, when you are loading a custom css file, you have to know what you are doing. And for someone it means they can slightly change the default font size and type to make it more readable, as where others change the layout a bit more to their needs.

**Comment by jeroenstoker** [comment]
What I see is this:

**2 fields in the database**
- customCssActive (Boolean)
- customCssUrl (Text/varchar 256)

In the main template before the </body> tag

```
If (customCssActive == true && customCssUrl != “”) {
  echo ‘<link rel=“stylesheet” type=“text/css” href=“’.customCssUrl’”>’
}
```

**Comment by phpeter42** [comment]
This would be awsome!

**Comment by xet7** [comment]
Currently many are asking that if they upgrade to newest Wekan:
- Is there some known issues that something will break?
- Is there some way that it's possible to permanently delete data? (yes there still is, by using delete, not archive)
- Are there some bugs that could cause board not load? (those are currently being fixed)
- Could there be some tests added to Wekan?

In general, new versions of Wekan are safer that new versions to some other software, [according to  feedback from Cloudron](https://news.ycombinator.com/item?id=22887882).

If I would add Custom CSS, there are these open questions:
- How do I make sure any random admin adding CSS to Wekan knows what he/she is doing?
- How do I validate that CSS to make sure it does not break any existing Wekan features?

Currently changing background color, theme, card color etc is safe.

There are very often major changes to Wekan UI, CSS etc when adding major features.

I'm not so convinced yet that adding big security hole and a way to break Wekan with Custom CSS to Wekan for just 150 euro is worth it. It's me that is trying to provide support to Wekan, so I'm stright on the line when someone has given machine gun to teenager. I'm much more happy with adding some font etc menu options to Wekan.

Currently Wekan Snap version is installed to 8818 servers. I do know the feeling when some new Wekan version breaks something and Wekan users keep adding issues and comments about that bug.

It's not so easy as adding Custom CSS to one place. When adding themes to Wekan, CSS changes have been required to be places at correct files where is releated CSS, like card CSS. I don't even know would this really work.

Sure, if someone really knows what he/she is doing, and has ideas how to add Custom CSS to Wekan in a way that nothing can break, ideas welcome.

**Comment by xet7** [comment]
Hmm, just in case, I'll just add that the comment above is not directed to anyone and it's not in any way personal. I'm just trying to find a safe solution.

**Comment by helioguardabaxo** [comment]
A alternative is create a "Custom theme" that permits customize CSS classes theme directy in application.
In Admin Panel > Settings > Layout > Edit custom theme, the user could edit just the value fields, for example:

Custom theme editor:
  /* minicards */
  .minicard
    background-color:**VALUE**
  .minicard-wrapper.is-selected .minicard,
  .minicard:hover,
  .minicard-composer.js-composer,
  .open-minicard-composer:hover
    background-color:**VALUE** !important
    color:#**VALUE**
  .minicard, .minicard .badge
    color:#**VALUE**
  .minicard:hover .badge, .minicard-wrapper.is-selected .badge
    color:#**VALUE**

  /* cards */
  .card-details .card-details-header
    background-color:#**VALUE**

In Change Board Backgroud the user select Custom:
![Screenshot_2020-05-16 Quadro teste 2 - Kanban UFABC](https://user-images.githubusercontent.com/24301085/82125736-74d4d480-977e-11ea-944a-18667a7cd943.png)

**Comment by xet7** [comment]
@helioguardabaxo 

Yes. I'll list here related issues. I will be working on some of these, and all Wekan contributors are also encouraged to contribute to making all this happen, with pull requests or funding.

## API
- [ ] [Change all below settings both with UI and API](https://github.com/wekan/wekan/issues/3062)

## Images
- [ ] [Background image](https://github.com/wekan/wekan/issues/486#issuecomment-590308450)
- [ ] Background color range slide, like in Clearblue theme
- [ ] Import/Export background image from/to other kanban software etc
- [ ] [Change logo](https://github.com/wekan/wekan/issues/1493) at pages: Login, All Boards, Board etc certain places

## Colors
- [ ]  [More board icon colors to All Boards page](https://github.com/wekan/wekan/issues/2796)
- [ ]  [Natural theme](https://github.com/wekan/wekan/issues/2592)
- [ ]  [Color around avatar](https://github.com/wekan/wekan/issues/2110)
- [ ]  [Multiselection to change color of cards](https://github.com/wekan/wekan/issues/2160)

## UI Style
- [ ] [Card and other dialogs to use fullscreen, to have more visible at once](https://github.com/wekan/wekan/issues/1574#issuecomment-609095074)
- [ ] [Customized Card Style](https://github.com/wekan/wekan/issues/2509)
- [ ] Removing the x (close) buttons where it is absolute
- [ ] Margins
- [ ] Padding
- [ ] Change line height
- [ ] Change the border radius of elements the adjust it to branding
- [ ] Change icon sizes in mobile version

## Fonts
- [ ]  [Change Fonts](https://github.com/wekan/wekan/issues/914)
- [ ]  Change the fonts and titles of the tiles
- [ ]  Change Font Colors

**Comment by helioguardabaxo** [comment]
@xet7 
I create a PR to resolve #2592

I really liked @jeroenstoker UI proposal, especially on the minicard and card-date

What do you think it's better?
Create a new theme or modify some elements for the whole system? Or none of these options?

**Comment by xet7** [comment]
@helioguardabaxo 

You just modify some elements for the whole system, affecting all themes. Then we just release it and wait for feedback is something not readable enough, and in general, does someone complain. You can create pull request for those UI changes, but not those forbidden changes for hiding things because those can already be modified in Board Settings / Card Settings.

**Comment by xet7** [comment]
@helioguardabaxo 

Do not hide that X close button. It's very hard to close card etc if there is no X.

**Comment by xet7** [comment]
@helioguardabaxo 

Actually, first you could try adding it as separate theme, to see what it looks like.

**Comment by xet7** [comment]
@helioguardabaxo 

Previously when I made some change that affected all themes, I had to revert it. So I think it's better to have separate theme, and sometime later add specific custom theme options like color etc.

**Comment by helioguardabaxo** [comment]
@xet7 
Perfect!
I am going create a new theme. With X close button. ;)
Thanks for your help!

**Comment by helioguardabaxo** [comment]
@jeroenstoker 
I am working in new theme with your suggestions.
Look here:
![Captura de tela de 2020-05-17 11-36-06](https://user-images.githubusercontent.com/24301085/82151709-35b48b00-9833-11ea-9d31-f5efd924ea7e.png)

I remove box-shadow and background of .list-body .open-minicard-composer:hover class
What do you think?

Have you other suggestions?

**Comment by jeroenstoker** [comment]
Ah, very nice @helioguardabaxo !! Thank you! 

I will make some more small changes and post them here. Or should we open an other issue named “Small UI Improvements” or something since this current issue is more about custom css? (Your call @xet7 )

I do believe the the design can be better, that is why I started this issue in the first place. But I don’t want to bother somebody else with my way of thinking. (Like the close button for example ;-)).

**Comment by xet7** [comment]
Well, I listed quite many changes, so it probably is not small.

**Comment by helioguardabaxo** [comment]
I managed to insert the Poppins font.
Ideally, all elements should have the same font-family?

![Captura de tela de 2020-05-17 16-48-08](https://user-images.githubusercontent.com/24301085/82158522-d3717f80-985e-11ea-9853-c881a4146ad5.png)

**Comment by xet7** [comment]
@helioguardabaxo 

What operating system has Poppins font? I have not heard about that font.

By default Wekan has Roboto font included.

There should be some option to write font name, it should not be hardcoded.

**Comment by helioguardabaxo** [comment]
I don't think any operating system has that font. I did it like this:
- I downloaded the font file in / public / fonts.
- I added the code in fonts.styl:
@ font-face
   font-family: 'Poppins'
   font-style: normal
   font-weight: 400
   src: local ('Poppins'),
        local ('Poppins-Regular'),
        url ('/ fonts / poppins-regular.woff') format ('woff')

@ font-face
   font-family: 'Poppins'
   font-style: normal
   font-weight: 700
   src: local ('Poppins Bold'),
        local ('Poppins-Bold'),
        url ('/ fonts / poppins-bold.woff') format ('woff')

- Added Poppins to layouts.styl:
html, body, input, select, textarea, button
   font: 14px Roboto, Poppins, "Helvetica Neue", Arial, Helvetica, sans-serif
   line-height: 18px
   color: # 4d4d4d

- I added in the respective classes:
font-family: Poppins

Would the correct way be to use a font that is available on multiple OS?

**Comment by xet7** [comment]
@helioguardabaxo 

That depends on license of that font, is including to Wekan allowed. Paid fonts can not be included in Wekan, it would most likely be expensive.

**Comment by xet7** [comment]
Also if that license has some non-commercial license, so it does not allow commercial use, that can not be used. Wekan is used also at commercial use.

**Comment by xet7** [comment]
For current Roboto font, I did previously add new version of it to Wekan, to add support for more languages in the font.

**Comment by helioguardabaxo** [comment]
According to Google Fonts, the font contains Open Font Licence.

https://fonts.google.com/specimen/Poppins?selection.family=Roboto:wght@100;400;700&sidebar.open&query=poppins

"
These fonts are licensed under the Open Font License.
You can use them freely in your products & projects - print or digital, commercial or otherwise. However, you can't sell the fonts on their own.
This isn't legal advice, please consider consulting a lawyer and see the full license for all details.
"

**Comment by brianrc** [comment]
WordPress allows admins to add css and even (gasp) edit the entire code base of php plugins and themes in it's interface. So yeah, admins could break things with bad css, but that comes with the territory of modifying any code. A big fat warning would probably suffice. 

On the issues of updates, I might suggest adding a little dismissible notice shown only to admins whenever there is an update. It could include a link to a changelog so admins could see any changes (with credits and a donate link :) ).

I do think it would be better to try to incorporate most design improvements into the program itself, though, so we can all benefit!

**Comment by helioguardabaxo** [comment]
@xet7 @jeroenstoker 
I have a doubt:
Is it ideal to have a same font for the entire theme?
If so, I should define the font for the elements (p, h1, h2, h3, span, etc.) or for each of the classes, like the example below:
  .list-header .list-header-name
     font-family: Poppins

**Comment by jeroenstoker** [comment]
@helioguardabaxo I think that won’t be necessary.

It is a nice font for headings I think. I would not recommend Poppins for a body font. And for the content (p etc.) I think Roboto (that is currently used) is better. It has more balanced spacing and the thickness is more constant which makes it better readable.

**Comment by helioguardabaxo** [comment]
@jeroenstoker 
Do you use dark theme in Wekan?
What you think a dark theme based in your suggestions?
I tested Ubuntu Dark Theme colors in default theme: 
 
![Screenshot_2020-05-17 Quadro teste 2 - Kanban UFABC](https://user-images.githubusercontent.com/24301085/82754922-9a796380-9da6-11ea-9c05-b496bab73c44.png)

**Comment by jeroenstoker** [comment]
So far I havent used it yet. But what you are showing looks good! It has enough contrast I think :-)

**Comment by jeroenstoker** [comment]
@helioguardabaxo I have made some small changes on the Modern Theme here

[extra.css.txt](https://github.com/wekan/wekan/files/4681734/extra.css.txt)

**Comment by helioguardabaxo** [comment]
@xet7 @jeroenstoker 
Thanks!

**Comment by ruihildt** [comment]
I'm all for improving the design of the overall app like you're doing, and I'm stocked by the progress being made here.

At the same time, I'd still recommend having a `custom css` zone available for the admin.
If there's a warning it can break across versions and that no support will be given to people using custom css, we should trust admins. :)

**Comment by helioguardabaxo** [comment]
At the same time, I'd still recommend having a custom css zone available for the admin.
If there's a warning it can break across versions and that no support will be given to people using custom css, we should trust admins. :)

**Comment by jghaanstra** [comment]
Just chipping in here with an opinion and a few bucks to support this feature.

> A alternative is create a "Custom theme" that permits customize CSS classes theme directy in application.
> In Admin Panel > Settings > Layout > Edit custom theme, the user could edit just the value fields, for example:
This would be very nice as @helioguardabaxo already suggested and should limit the concerns about breaking anything.

I still think having a way to save custom CSS to the database (not an external file) is the most flexible solution, best even in combination with the alternative as described above. With some validation on this field the security risk is minimal.

**Comment by xet7** [comment]
@jghaanstra 

Huh? What kind of validation can prevent it from breaking anything?

**Comment by jghaanstra** [comment]
> @jghaanstra
> 
> Huh? What kind of validation can prevent it from breaking anything?

By using a javascript code editor (like CodeMirror, Ace editor, etc.) you can do syntax validation to make sure it's valid CSS and CSS only.

**Comment by xet7** [comment]
@jghaanstra

Well, because someone figured out how to send some bucks to me (poor Open Source developer), as a start I wrote this beginner info below how to try to shoot pull request without hitting foot:

- from [Part1](https://github.com/wekan/wekan/pulls/3335) and [Part2](https://github.com/wekan/wekan/commit/6801c960b115be4265bf18ba05c444ac79aef887) you see how to add theme
- from [this you see how to add Layout setting](https://github.com/wekan/wekan/commit/4cfddf1d8d37bdbbb58c050333ee6ea2afc3e6f9)
- But currently [main color table is hardcoded](https://github.com/wekan/wekan/blob/master/server/migrations.js#L125)
- That [maincolor is set here in function](https://github.com/wekan/wekan/blob/master/client/components/boards/boardColors.styl#L750)
- So maybe you need to set that mainColor and customCss [like this](https://github.com/wekan/wekan/blob/master/client/components/main/layouts.jade#L30), `style="{{currentSetting.customCss}}"`
- Maybe [this sanitizeXss function](https://github.com/wekan/wekan/issues/3218#issuecomment-724956665) could be used to remove all Javascript from CSS.

**Comment by brian-j** [comment]
From the same author that developed the sanitizeXss function:

[Sanitize untrusted CSS with a configuration specified by a Whitelist.](https://github.com/leizongmin/js-css-filter)

**Comment by diegopau** [comment]
> At the same time, I'd still recommend having a custom css zone available for the admin.
> If there's a warning it can break across versions and that no support will be given to people using custom css, we should trust admins. :)

Maybe this is a good idea?

The way bookstack does it is that it allows to insert custom code in the <head> section of every page from the admin settings. In case this breaks anything all this custom code applies to all pages except the admin area, so when you are in the admin area you don't see any of your custom CSS and or other code and it will always work. Here is how it looks like for our bookstack instance:

![image](https://user-images.githubusercontent.com/315149/117192021-8bd26380-ade1-11eb-8b44-bef1574894d3.png)
