### ISSUE TITLE
TODO: Meteor 2.7.1 WeKan Progress at meteor-upgrade branch

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#4485]
## TODO: Try to fix these that do not work in Meteor 2.7.1 WeKan
- [x] Adding Label and Label Color, at card and at sidebar
- [x] Languages menu does not show all language names
- [x] Changing from English to another language does not work
- [x] `meteor` terminal log shows `The package kenton:accounts-sandstorm at 0.1.0 is incompatible with Meteor 0.9.0 or later`
- [x] `meteor` terminal log shows `i18next: languageChanged en`, list of languages etc language output

<details>
  <summary>Translations output details</summary>
  
```
I20220418-22:53:08.231(3)? i18next: languageChanged en
I20220418-22:53:08.232(3)? i18next: initialized {
I20220418-22:53:08.233(3)?   debug: true,
I20220418-22:53:08.234(3)?   initImmediate: true,
I20220418-22:53:08.234(3)?   ns: [ 'translation' ],
I20220418-22:53:08.235(3)?   defaultNS: 'translation',
I20220418-22:53:08.235(3)?   fallbackLng: [ 'en' ],
I20220418-22:53:08.236(3)?   fallbackNS: false,
I20220418-22:53:08.236(3)?   supportedLngs: [
I20220418-22:53:08.237(3)?     'ar-EG',  'ar',    'bg',    'br',    'ca',    'cs',
I20220418-22:53:08.237(3)?     'da',     'de-AT', 'de-CH', 'de',    'el-GR', 'el',
I20220418-22:53:08.237(3)?     'en-DE',  'en-GB', 'en-IT', 'en',    'eo',    'es-AR',
I20220418-22:53:08.238(3)?     'es-CL',  'es-LA', 'es-MX', 'es-PE', 'es-PY', 'es',
I20220418-22:53:08.238(3)?     'et-EE',  'eu',    'fa-IR', 'fa',    'fi-FI', 'fr-BE',
I20220418-22:53:08.239(3)?     'fr-CA',  'fr-CH', 'fr',    'gl-ES', 'gl',    'gu-IN',
I20220418-22:53:08.239(3)?     'he',     'hi-IN', 'hi',    'hr',    'hu',    'hy',
I20220418-22:53:08.239(3)?     'id',     'ig',    'it',    'ja',    'ka',    'km',
I20220418-22:53:08.239(3)?     'ko',     'lt',    'lv',    'mk',    'mn',    'ms-MY',
I20220418-22:53:08.239(3)?     'nb',     'nl',    'oc',    'pa',    'pl',    'pt-BR',
I20220418-22:53:08.239(3)?     'pt',     'ro',    'ru-UA', 'ru',    'sk',    'sl',
I20220418-22:53:08.240(3)?     'sr',     'sv',    'sw',    'ta',    'th',    'tr',
I20220418-22:53:08.240(3)?     'ua-UA',  'ua',    'vi',    'zh-CN', 'zh-HK', 'zh-TW',
I20220418-22:53:08.240(3)?     'cimode'
I20220418-22:53:08.240(3)?   ],
I20220418-22:53:08.241(3)?   nonExplicitSupportedLngs: false,
I20220418-22:53:08.241(3)?   load: 'all',
I20220418-22:53:08.241(3)?   preload: false,
I20220418-22:53:08.241(3)?   simplifyPluralSuffix: true,
I20220418-22:53:08.241(3)?   keySeparator: '.',
I20220418-22:53:08.241(3)?   nsSeparator: ':',
I20220418-22:53:08.241(3)?   pluralSeparator: '_',
I20220418-22:53:08.242(3)?   contextSeparator: '_',
I20220418-22:53:08.242(3)?   partialBundledLanguages: false,
I20220418-22:53:08.242(3)?   saveMissing: false,
I20220418-22:53:08.242(3)?   updateMissing: false,
I20220418-22:53:08.242(3)?   saveMissingTo: 'fallback',
I20220418-22:53:08.242(3)?   saveMissingPlurals: true,
I20220418-22:53:08.242(3)?   missingKeyHandler: false,
I20220418-22:53:08.243(3)?   missingInterpolationHandler: false,
I20220418-22:53:08.243(3)?   postProcess: [ 'sprintf' ],
I20220418-22:53:08.243(3)?   postProcessPassResolved: false,
I20220418-22:53:08.243(3)?   returnNull: true,
I20220418-22:53:08.243(3)?   returnEmptyString: true,
I20220418-22:53:08.243(3)?   returnObjects: false,
I20220418-22:53:08.243(3)?   joinArrays: false,
I20220418-22:53:08.244(3)?   returnedObjectHandler: false,
I20220418-22:53:08.244(3)?   parseMissingKeyHandler: false,
I20220418-22:53:08.244(3)?   appendNamespaceToMissingKey: false,
I20220418-22:53:08.244(3)?   appendNamespaceToCIMode: false,
I20220418-22:53:08.244(3)?   overloadTranslationOptionHandler: [Function: handle],
I20220418-22:53:08.244(3)?   interpolation: {
I20220418-22:53:08.244(3)?     escapeValue: false,
I20220418-22:53:08.245(3)?     format: [Function: bound format],
I20220418-22:53:08.245(3)?     prefix: '__',
I20220418-22:53:08.245(3)?     suffix: '__',
I20220418-22:53:08.245(3)?     formatSeparator: ',',
I20220418-22:53:08.245(3)?     unescapePrefix: '-',
I20220418-22:53:08.245(3)?     nestingPrefix: '$t(',
I20220418-22:53:08.246(3)?     nestingSuffix: ')',
I20220418-22:53:08.246(3)?     nestingOptionsSeparator: ',',
I20220418-22:53:08.246(3)?     maxReplaces: 1000,
I20220418-22:53:08.246(3)?     skipOnVariables: true
I20220418-22:53:08.246(3)?   },
I20220418-22:53:08.246(3)?   cleanCode: true,
I20220418-22:53:08.247(3)?   defaultNs: 'translation',
I20220418-22:53:08.247(3)?   resources: {},
I20220418-22:53:08.247(3)?   ignoreJSONStructure: true,
I20220418-22:53:08.247(3)?   lng: 'en'
I20220418-22:53:08.247(3)? }
```
</details>

- [x] All Boards / Duplicate Board does not work, shows error:

<details>
  <summary>Duplicate Board error details</summary>

```
Exception in delivering result of invoking 'copyBoard': TypeError: self.setError is not a function
    at boardsList.js:263:22
    at MethodInvoker._callback (meteor.js?hash=b9ec8cf25b6fc794ae6b825f30e06c3c35c50e7c:1236:22)
    at MethodInvoker._maybeInvokeCallback (MethodInvoker.js:52:12)
    at MethodInvoker.dataVisible (MethodInvoker.js:79:10)
    at livedata_connection.js:1354:38
    at livedata_connection.js:1221:7
    at Array.forEach (<anonymous>)
    at Connection._runAfterUpdateCallbacks (livedata_connection.js:1220:15)
    at Connection._performWrites (livedata_connection.js:1210:10)
    at Connection._flushBufferedWrites (livedata_connection.js:1162:10)
```
</details>

- [x] Browser right click inspect console errors about Sandstorm accounts:

<details>
  <summary>Sandstorm accounts error details</summary>

```
Uncaught TypeError: Cannot read properties of undefined (reading 'write')
    at kenton_accounts-sandstorm.js?hash=d71d6157a0e8fb4b003b7b58f9178bba031dc8c5:34:16
    at kenton_accounts-sandstorm.js?hash=d71d6157a0e8fb4b003b7b58f9178bba031dc8c5:42:4
    at kenton_accounts-sandstorm.js?hash=d71d6157a0e8fb4b003b7b58f9178bba031dc8c5:46:4
    at kenton_accounts-sandstorm.js?hash=d71d6157a0e8fb4b003b7b58f9178bba031dc8c5:52:3
```  
</details>

- [x] Browser right click inspect console errors about mermaid, translations and moment::

<details>
  <summary>Mermaid, translations and moment errors details</summary>

```
mermaid.esm.min.mjs:2 i18next: languageChanged en
mermaid.esm.min.mjs:2 i18next: initialized Object
mquandalle_moment.js?hash=d64fcd3effe00da3e5678c98bec83265d29b7ff1:3157 Uncaught TypeError: Cannot read properties of null (reading 'toLowerCase')
    at mquandalle_moment.js?hash=d64fcd3effe00da3e5678c98bec83265d29b7ff1:3157:72
    at Computation._compute (tracker.js:308:7)
    at new Computation (tracker.js:206:12)
    at Object.Tracker.autorun (tracker.js:576:11)
    at mquandalle_moment.js?hash=d64fcd3effe00da3e5678c98bec83265d29b7ff1:3155:13
    at maybeReady (meteor.js?hash=b9ec8cf25b6fc794ae6b825f30e06c3c35c50e7c:943:28)
    at HTMLDocument.loadingCompleted (meteor.js?hash=b9ec8cf25b6fc794ae6b825f30e06c3c35c50e7c:955:5)
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation app-is-offline app-is-offline
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation app-try-reconnect app-try-reconnect
cardSearch.js:74 session data: Document
cardSearch.js:86 debug: null
cardSearch.js:87 debug.show(): false
cardSearch.js:88 debug.showSelector(): false
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation Card Card
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation List List
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation Board Board
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation Swimlane Swimlane
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation Members Members
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation Labels Labels
mermaid.esm.min.mjs:2 i18next::translator: missingKey en translation Due Date Due Date
cardSearch.js:74 session data: Document
cardSearch.js:86 debug: null
cardSearch.js:87 debug.show(): false
cardSearch.js:88 debug.showSelector(): false
modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:232 Uncaught (in promise) Error: Cannot find module './data/fi-FI.i18n.json'
    at makeMissingError (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:232:12)
    at Module.resolve (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:238:17)
    at modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:164:31
    at new Promise (<anonymous>)
    at Module.prefetch (modules-runtime.js?hash=23fe92393aa44a7b01bb53a510a9cab5fb43037c:163:34)
    at Module.dynamicImport (dynamic-import.js?hash=af116059a0e60828fb1fb1c12746ea4f7f4bbcaa:48:17)
    at Object.load (languages.js:174:17)
    at Object.loadLanguage (tap.js:43:46)
    at Object.setLanguage (tap.js:48:16)
    at constructor.onCreated (boardsList.js:37:15)
```
  
</details>

**Comment by xet7** [comment]
Others:
- https://github.com/wekan/wekan/issues/4061
- https://github.com/wekan/wekan/issues/1298
- https://github.com/wekan/wekan/issues/4357

**Comment by xet7** [comment]
Moved to here from https://github.com/wekan/wekan/pull/4482#issuecomment-1105458571

From @imajus

I've fixed a few listed issues:

- [x] Languages menu does not show all language names
- [x]  Changing from English to another language does not work

From @xet7 

I have added these changes to meteor-upgrade branch. For future changes, please add new PRs for meteor-upgrade branch. I'm currently merging some newest changes from master to meteor-upgrade branch.

**Comment by imajus** [comment]
I see that there are some packages which was removed temporary during previous Meteor 2.3 upgrade attempt, but they could be necessary for system to work properly:

- [ ] kenton:accounts-sandstorm
- [ ] wekan-ldap
- [ ] wekan-accounts-cas
- [ ] wekan-accounts-oidc

Should we return them back and make work with the latest Meteor version prior to merging this branch?

**Comment by xet7** [comment]
@imajus 

Maybe, if possible. They have many WeKan-specific environment settings and compatibility with many auth providers. They could be added back this way:

1) Copy them from master branch wekan/packages/ to meteor-update wekan/packages. `kenton:accounts-sandstorm` package can be found from atmospherejs.com

2) At meteor-update branch directories `wekan/packages/PACKAGENAME/packages.js` , change:
- Package version numbers to compatible newest Meteor package numbers, same as at `wekan/.meteor/packages` or `wekan/.meteor/versions`
- Update syntax, like `add_files` to `addFiles`
- If package does not have local forked package name like `wekan-ldap`, change package name, so that it does not have `:` like at `kenton:accounts-sandstorm`
- If package name is not listed at `wekan/.meteor/packages`, add it there with command like `meteor add wekan-ldap`

Also would be good to get back working this package, that has brute force login protection:

- [ ] meteor-accounts-lockout

Another way would be to look at newest Meteor docs, are there newer auth packages, are they in some way better? For example, there is also some 2fa package available for newest Meteor.

**Comment by xet7** [comment]
I have done these:
- Added newest changes like https://github.com/wekan/wekan/pull/4484 from master to meteor-update branch
- Added all newest languages from Transifex to WeKan. Someone requested to be added about 30 new languages, including some romance language, some African languages, etc. I hope that someone will have time to translate those. But I'm still thinking, nobody has yet requested [Klingon language](https://blog.wekan.team/2018/02/time-well-spent/), I would like to have help with adding that. Anyway, now there is about 105 languages at WeKan. I have not added those new languages to master branch, I presume meteor-upgrade branch will sometime merged to master.
- I did check that adding Labels now works, maybe @imajus fixed it.
- I did update [Mermaid](https://github.com/wekan/wekan/wiki/Mermaid-Diagram) to newest version, but there could maybe still be errors about that.

**Comment by xet7** [comment]
I have not checked is meteor-accounts-lockout similar like some rate limiting feature that is at newest Meteor docs.

**Comment by xet7** [comment]
I added --trace-warnings to see where those errors are when using `meteor` command during development https://github.com/wekan/wekan/commit/3fb709ed70d8a2a823116bb348f7a02b1600afa9

**Comment by mfilser** [comment]
@xet7
I am having a look at the upgrade-meteor branch right now and saw there are some issues with attachments after the merge of #4484 
I will also look at the attachment issues. 

I don't know your release plan, but if i can make a suggestion i prefer to make a release before making a release with changes by upgrade-meteor branch.

**Comment by xet7** [comment]
@mfilser 

I don't know can I make release on master branch anymore, it seems very slow with all those 105 languages, even when running on Chrome on server KVM VM that has nproc 20 and 60 GB RAM. upgrade-meteor branch works with that amount of languages, maybe it loads only one language. I presume it depends can master or upgrade-meteor branch be fixed enough, or does some of my rewrite prototypes get enough features to become replacement.

**Comment by xet7** [comment]
Hmm, anyway, I'll try making release on master branch, to see does it work.

**Comment by xet7** [comment]
In Sandstorm WeKan v6.19, it seems some .png images are broken, they were visible and correctly migrated in previous WeKan.

**Comment by xet7** [comment]
Docker does not build, I'm getting some errors when doing:
```
git clone https://github.com/wekan/wekan
cd wekan
docker build .
```
And also WeKan Gantt GPL version has some errors:
```
git clone https://github.com/wekan/wekan-gantt-gpl
cd wekan
docker build .
```
Those do stop to some error.

For successful build, those show container ID at end of build, and I use `wekan/releases/docker-push*.sh` scripts at https://github.com/wekan/wekan to push those to Docker Hub and Quay.io , when I'm logged into Docker Hub and Quay.io .

Help welcome to figure out why it does not build.

**Comment by xet7** [comment]
Source bundles did build correctly, those are at https://releases.wekan.team , and docs at https://github.com/wekan/wekan/wiki/Raspberry-Pi and https://github.com/wekan/wekan/wiki/Offline and https://github.com/wekan/wekan/wiki/Mac

**Comment by mfilser** [comment]
@xet7
If you like I would have a look at Docker build.

**Comment by mfilser** [comment]
Do you mean current master branch or upgrade-meteor branch?

**Comment by xet7** [comment]
@mfilser 

master branch, that I released. There are problems with Docker builds and Sandstorm WeKan attachments.

I can not release upgrade-meteor branch, it does not have login/auth features.

**Comment by mfilser** [comment]
@xet7
Which errors do you get at Docker builds and which at Sandstorm Wekan Attachments?

**Comment by xet7** [comment]
@mfilser 

Some Sandstorm WeKan attachments are not visible anymore in this newet WeKan.

I did not save Docker build logs, they had errors. This way it's possible to build Docker WeKan and see errors https://github.com/wekan/wekan/issues/4485#issuecomment-1106688719

**Comment by mfilser** [comment]
@xet7
I will think about the attachment problem and send a PR soon when solved. Same for docker build.

**Comment by mfilser** [comment]
@xet7
I guess docker build is also solved through #4488 and https://github.com/wekan/wekan/commit/79a866e2384d262572edf68503f31e699df675eb, or?

**Comment by xet7** [comment]
@mfilser 

Yes, Docker WeKan did build successfully, I pushed it to Docker Hub and Quay.io .

**Comment by mfilser** [comment]
@xet7
Great. I had it already in my mind, but didn't test it fully, i had also successfull builds with ubuntu:rolling

**Comment by xet7** [comment]
@mfilser 

Well, I did not test it yet. For me, building Docker images did not work with `ubuntu:rolling`, they only worked with `ubuntu:21.10` . Usually someone adds new issue, if something does not work.

**Comment by mfilser** [comment]
By the way. Redeploy on code change is with Meteor 2.7.2 very very fast, amazing, only about 8 seconds now, before it took about 2 minutes.
Do you know @xet7 what changed at Meteor why this is so pretty fast now?

**Comment by xet7** [comment]
Although, upgrade-meteor does not have all the dependencies it had originally.

Some meteor build being slow can be because some dependency does some not needed time consuming stuff, it can be just a bug, for example newer Stylus version taking extra 52 minutes when building:
https://github.com/wekan/wekan/blob/master/.meteor/packages#L82-L83

**Comment by mfilser** [comment]
I see, thank you. I think there are a few things which speedy up the redeploy.
It's great, and very comfortable while developing 🙂

**Comment by mfilser** [comment]
I am working on "Copy Board" issue. PR comes the next days.
