### ISSUE TITLE
Add Feature: Teams/Organizations similar to Trello

### ISSUE THREAD

**Issue by xet7** [wekan/wekan#802]
_From @aegrey on December 18, 2016 1:53_

### Feature Description   
Similar to Trello, an administrator would be able to create a Organization/Team/User. Any boards created under this team would be accessible to all members of the team. Very high level of changes would be:

- [ ] Organizations: Add/Modify/Remove in Admin Panel.
- [ ] Teams: Add/Modify/Remove in Admin Panel. Board overview page would be available for the team, similar to the users, but with additional controls to manage the team members.   
- [ ] Teams: Privacy: Private/Public. With Private option, making board public is not allowed.
- [x]  Users: Modify in Admin Panel, change password.
- [x]  Users: Add in Admin Panel.
- [ ]  Users: When adding, also save fullname.
- [ ]  Users: Remove in Admin Panel. There is Error after deleting a user #1289
- [ ] LDAP: Subgroups https://github.com/wekan/wekan-ldap/issues/58
- [ ] LDAP: map unlimited Wekan profile items to LDAP fields. If profile is changed in Wekan, should Wekan have ability to save data back to LDAP? Or should Wekan be able to override LDAP settings? https://github.com/wekan/wekan-ldap/issues/58
- [ ] LDAP: Map Wekan Roles to LDAP Roles https://github.com/wekan/wekan-ldap/issues/58
- [ ] LDAP: Check that only Admin LDAP subgroup gets Wekan Admin permissions https://github.com/wekan/wekan-ldap/issues/58#issuecomment-495890729
- [ ] LDAP: Check that LDAP filter works correctly. Is it possible to simplify filter settings? https://github.com/wekan/univention/issues/5

### Discussion Requests      
https://discourse.wekan.io/t/teams-and-permissions/77 (somewhat similar)     
https://discourse.wekan.io/t/any-progress-on-users-being-able-to-see-and-interact-all-boards-immediately-upon-registration-suggestion-groups/206      
     
    
I currently don't know of any code bases that would assist in implementation of this feature, but this is the main reason why I'm still using Trello for my team, so I'd like to contribute. I did not see any pull request for it in the main repo. I know this would be a fairly heavy lift with database restructuring necessary.   
    
If this isn't something someone currently has on their radar, I have forked this repo and will plan on documenting the technical requirements to implement this feature, and then communicate this and possibly start implementation of the feature as time allows. 

_Copied from original issue: wefork/wekan#52_

**Comment by xet7** [comment]
@aegrey 

This is related to other Wefork issues in this way:

#13 Has some code for admin interface, but probably does not include teams

For making Wefork programmable, AFAIK there is no code for these yet:

#43 API

#42 Using Email with API

#49 Auto add user name to a moved card

There is currently not much technical documentation of Wefork, only some related to using it at:
https://github.com/wefork/wekan/wiki/FAQ
https://github.com/wefork/wekan/wiki/Install-from-source

And also on original Wekan wiki:
https://github.com/wekan/wekan/wiki

Wefork code is mostly Javascript, templates, CSS and some YAML. It uses Meteor Javascript framework, Node.js for serverside, and MongoDB database that also is Javascript-based.

On codebase, there is check for environment variable, is it running:
1) Wekan standalone version, when it has multiboard features, login etc etc although disabling login on #13 is not implemented yet.
2) Running on Sandstorm, then only one board is in use and is set to public, because Sandstorm provides authentication, sandboxing in grains etc.

Wefork code is quite logically divided to subfolders. I recommend that after cloning that repo to your computer:
1) You don't add Node.js modules or Meteor framework to there
2) Read the code and make notes

If possible, it would be nice to have additional MongoDB database collections (or "tables" as in SQL database terms) for additional information added, that would make upgrading from previous versions of Wefork easier. Some users have a lot of data. So in new version if collection does not exists, then create it.

Planning and documenting technical requirements would be a good way to start. This would also prevent duplicate work when Team/Organization admin is different than the simple previous #13 implementation.

Currently Wefork team is quite small, so having some new technical documentation of code structure would also help newcomers to get familiar with it.

**Comment by aegrey** [comment]
Thanks @xet7 - I've been looking over the code and am halfway through some tech specs for this, I've been busy but I'll post something when I put together something more solid if someone else doesn't take it on first. :)

**Comment by xet7** [comment]
@aegrey 

Thanks! It's very nice to get tech specs for this.

Since your previous post to this issue Wekan has [gained many more features](https://github.com/wekan/wekan/wiki/Features), I will also add there recent [ability to change email address](https://github.com/wekan/wekan/pull/1161).

**Comment by killua-eu** [comment]
Added a bounty on this issue. Please see https://www.bountysource.com/teams/wekan/issues ...

**Comment by xet7** [comment]
Moved to here from #1220 

Feature request by @DukeW

> It would be nice to be able as an admin to take "ownership" of boards. I have a Wekan instance running for 30 people, and some people don't archive there boards when there done. I would like to be able to take ownership of these old boards and archive them my self. Also sometimes a board creator is not present and new people need to be added to a board, right now I don't have a way of doing this.

Reply by @xet7

> It's possible to change you as board admin [at MongoDB database](https://github.com/wekan/wekan/issues/1060#issuecomment-310545976), that link is mentioned at [Platforms page](https://github.com/wekan/wekan/wiki/Platforms). There is no Web UI for it yet. I have not tried can it be done with [REST API](https://github.com/wekan/wekan/wiki/Features#api).

**Comment by xet7** [comment]
@aegrey 

Can you add your in-progress tech specs to this issue?

**Comment by xet7** [comment]
@thuanpq is working on this.

@thuanpq , please accept invitation to Wekan GitHub Organization so I can assign you to this issue.

**Comment by xet7** [comment]
Moved to here from #1397

From @Logicbloke 

> Hi,
As a project manager, I sometimes have to dispatch task to team members, but I'm mostly using one board per project rather than one board per team member. Why is it that any member added to the board with the normal permissions can edit other cards other than the ones assigned to him? To the very list bring the permissions down to the lists level.
>
> The comment permissions look OK for this kind of thing but it's preventing the team member for ticking the checklists.
> 
> Are kanban boards supposed to be one board per team member?
>
> Thanks!

@Logicbloke 

Please add details how this feature would work step by step, and add to bounty for this issue so there is enough funding for building these features, more details about bounties at http://www.xet7.org/wekan

**Comment by xet7** [comment]
Correction: ss+ is working on adding Teams/Groups feature.

Afaik @thuanpq is not working on this feature.

**Comment by AndyatFocallocal** [comment]
I'm also actively following this issue. We weren't able to move from Trello as we needed the 'invite link' feature so visitors to our site could sign up and join a board. We haven't grown our dev team to the point where we can focus on building that feature, although we would join in your excellent work coding this project if we moved from Trello to Wekan

**Comment by xet7** [comment]
@AndyatFocallocal 

What 'invite link' feature? Please give link to existing or new issue about that.

**Comment by coolacid** [comment]
Re #1737 Thanks for moving. I tried to see the best place. Subbed to this one. :+1:

**Comment by d3dbit** [comment]
I am also interested in this feature.

**Comment by xet7** [comment]
If all goes well, I'll maybe get teams feature from ss+ next week, so I'll add this note to myself so I'll check 2018-07-27 did it happen.

**Comment by xet7** [comment]
I have some parts of teams feature in progress at https://github.com/wekan/wekan/tree/feature-teams . It still needs some work, Admin Panel part is not visible currently, etc.

**Comment by xet7** [comment]
Moved to here from https://github.com/wekan/wekan/pull/2029

From @saurabharch

> Admin can create credential of new user of team member and bypass the user verification, bcz some email transactional process is not working well so need new features like this.

@saurabharch Do you mean adding new user in Admin Panel ?

**Comment by mpathiuk** [comment]
I'd also like to be able to add new users in admin panel. As admin it would be good to be able to change 'verified' for email to 'yes' in the backend in the edit screen too.

**Comment by luke5sky** [comment]
@xet7 is there a workaround for deleting a user? Thank you for your help

**Comment by xet7** [comment]
@luke5sky 

I would recommed [disable user using API](https://github.com/wekan/wekan/wiki/REST-API-User#disable-a-user-the-user-is-not-allowed-to-login-and-his-login-tokens-are-purged)

It's also possible to [take ownership of users boards](https://github.com/wekan/wekan/blob/devel/models/users.js#L737-L752) but it's not documented well yet.

It's not recommeded to [delete user](https://github.com/wekan/wekan/wiki/REST-API-User#user-delete) because it can break Wekan board.

What should happen to user's data when user is deleted? It's not implemented properly yet.

**Comment by JonasDralle** [comment]
My Team would greatly benefit from this.
When will it roll out?

**Comment by xet7** [comment]
@JonasDralle @rterwedo

This feature is waiting for some interested ones to participate to bounty for this issue, so that I could start working on this, helping me to pay my bills.

https://wekan.team/bounties/index.html

https://www.bountysource.com/issues/41780380-add-feature-teams-organizations-similar-to-trello

**Comment by rterwedo** [comment]
@xet7 Whats the target bounty for this?

**Comment by xet7** [comment]
@rterwedo 

$700 so I can start

**Comment by rterwedo** [comment]
@xet7 I can try and get approval for some of it, but will take sometime.

**Comment by chotaire** [comment]
As an admin, I will need to be able to list boards, also hidden boards and add myself to these boards or take ownership. This is especially important if updates break the installation, to be able to browse for possible wreckage in existing boards (as seen in v2.30 update).

So I am also requested that these features are added to Wekan regardless of Teams/Organizations being implemented. An admin should always be able to do this. If you think this feature is too powerful, make it an optional flag? (e.g. superadmin)

**Comment by xet7** [comment]
Yes, I will add more details about superadmin etc when I think a little more about roles/permissions etc.

**Comment by rterwedo** [comment]
Consider the use case of separate "departments" that are usually independent with their own boards/templates etc and then users of a department.  That hierarchy is important.

**Comment by xet7** [comment]
@rterwedo 

How would whole structure go? For example:
Company Group / Company / Department / Organization / Team / User ?

Currently Wekan has these roles, what new ones are required?
- Admin (can delete)
- User (delete will be removed, only can archive)
- Comment Only
- No Comments

**Comment by xet7** [comment]
Actually, if whole structure is not known, other option is to make it possible to create and edit nested structure.

**Comment by xet7** [comment]
I think it would be good to have some screenshot mockups about what this should look like, for example with comparing to other Admin Panels. That way best one could be implemented.

**Comment by rterwedo** [comment]
Ah...  In an use case important to us you have:

 Parent (super admin, us) | Department (all departments similar but independent) | User (internal and maybe external)

For us we would template at the "Department" level  which also happens to be a separate company.  Each department would have boards/lists/swimlanes/cards etc pre-templated for them upon sign up.

**Comment by xet7** [comment]
@rterwedo

Maybe something like this:
```
Organization structure

List of levels:
Parent
Department *
User

New level name: ________  [Add]

Selected Level: Department

List of all at this level: 
Department 1 
Department 2

New Department name: _________ using [Board Group Template name (dropdown list)]
[Create]

Selected Department: Department 1
Permissions:
[_] Has Super Admin panel
[X] Has Admin Panel
[X] View all private boards of this level
[X] View all private boards of below levels
```

**Comment by AndyatFocallocal** [comment]
we've been asking for this for about 3 years now. i don't there's a lot of momentum here anymore, which is a shame, this was the one issue that stopped us using Wekan and a lot of users seem to think the same

**Comment by xet7** [comment]
@AndyatFocallocal 

You are the only one I have read to have such pessimistic opinion, I don't know in what kind of world you are living in.

- Wekan is critical part of new platforms Wekan is currently being integrated to.
- Wekan largest user has 13k users using Wekan in their company.
- Wekan has been translated to about 49 languages.
- Wekan is used in [most countries of the world](https://snapcraft.io/wekan).
- There is many companies and individuals contributing code to Wekan, to add features and bugfixes.
- There have been new features and fixes added to Wekan many times a day.

**Comment by JonasDralle** [comment]
There's nothing wrong with taking inspiration from our roots:

<details>
<summary>Screenshots: Teams on Trello</summary>

### Home

when going to the users home (e. g. clicking the logo)

![](https://user-images.githubusercontent.com/6533815/53656622-193f2980-3c54-11e9-9fb2-7df2b1b4c4ac.png)

### Team View

when clicking on the team from home

![](https://user-images.githubusercontent.com/6533815/53660184-8e632c80-3c5d-11e9-9c29-c3b11602dc8e.png)

### Team Overview

When clicking on "All Team Boards"

![](https://user-images.githubusercontent.com/6533815/53660357-fca7ef00-3c5d-11e9-9c2c-adf3f4ef5cde.png)

### Member Overview

another Tab in Team Overview

![](https://user-images.githubusercontent.com/6533815/53660729-e189af00-3c5e-11e9-98f1-15a4cd526f66.png)

### Settings

![](https://user-images.githubusercontent.com/6533815/53660811-10078a00-3c5f-11e9-860c-6fb1c5f569e5.png)
</details>

**Comment by JonasDralle** [comment]
Personally I see no need a reason to allow for nested teams / departments. LDAP-Style groups are probably sufficient.
Hierarchy-concerns are probably worth another Ticket.

**Comment by xet7** [comment]
- Hierarchy concerns #2186 , I do need hierarchy for my many use cases
- Tabbed UI #641

Wekan UI is different, so maybe some of the ideas could work, but in Trello screenshots above:
- there is too much repetition of text
- there is Change button, better would be to show the options to show available settings directly like in Wekan
- there is too little info shown at once at User Admin, Wekan Admin Panel does list more details about users at once
- Add board button is at bottom. I already a long time ago moved Add board button to top left, because otherwise it's needed to scroll to bottom of long list of boards to add new board.

**Comment by JonasDralle** [comment]
You're probably right about all of this. It's good that Wekan goes it's own way. Hopefully the screenshots are still worth something

**Comment by xet7** [comment]
@JonasDralle 

Of course they were worth it, screenshots gave me idea about tabbed UI. Thanks!

**Comment by rterwedo** [comment]
@JonasDralle LDAP could be overkill for simpler setups...you know some of us are lazy...  =)

**Comment by JonasDralle** [comment]
I said _LDAP-Style_ groups.
There's no need to reinvent the wheel. Plus being as close to LDAP as possible makes it espcially easy to add LDAP support later.

Consider [NextClouds User Management](https://docs.nextcloud.com/server/13/admin_manual/configuration_user/user_configuration.html)

![](https://docs.nextcloud.com/server/13/admin_manual/_images/users-groups.png)

Individual users can be in the group `Dev Department`, `Dev North` and `Bowling Fans` all at once and thus transcend between strict-hierarchical groups

**Comment by numidark** [comment]
Any news for ? : 
- Organizations: Add/Modify/Remove in Admin Panel.
- Teams: Add/Modify/Remove in Admin Panel. Board overview page would be available for the team, similar to the users, but with additional controls to manage the team members.

**Comment by xet7** [comment]
@numidark 

Well, my wish above is that some more would participate to bounty to this issue.

**Comment by rterwedo** [comment]
> @numidark
> 
> Well, my wish above is that some more would participate to bounty to this issue.

@xet7 Your wish is my command

**Comment by xet7** [comment]
Ok, I'm starting to develop this.

**Comment by xet7** [comment]
For example, specs this way:

For organizations feature it should be: Organization > Team > person
- When you add members to a board, you should be able to add an org / team / person to the board
- The list should be limited only to people who belong to your org or team
- You should not be able to add people to your board who aren’t on either your team or org
- Admins can see everything
- Org members can see all other org members
- Team members can see all other team members
- Team is owned by an org
- Members of cards should be either people or Teams
- An Org should not be a member of a card
- So for instance, if you have a Legal team who needs to review a card, but you don’t have a specific person assigned to the card, you can assign the actual legal Team to the card instead of a single person

Example of schema:
- https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/org_mig.go
- https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/team_mig.go

You’ll see they have 4 important tables:
- `org` which stores data about the org
- `org_user` which stores data about which users belong to which orgs
- `team` which has information about teams
- `team_member` which stores data about which users belong to which orgs

This is a successful way of managing users as well as permissions. You can assign board permissions to an entire group of people rather than individuals.

**Comment by xet7** [comment]
Permissions example:

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/migrations/dashboard_acl.go

- Here their "dashboard" would be equivalent to our "board"
- You see they can assign org, team, or user to the permission
- And the permission is assigned to the board
- The `role` field is the permission: View, Edit, Admin

**Comment by rterwedo** [comment]
@xet7 FYI if I miss something on releasing bounty, ping me.  I am moving halfway around the world with 2 babies...  a bit nuts atm.

**Comment by xet7** [comment]
@rterwedo 

Yes I will ping you after this feature is done. Currently it's still at beginning stage, adding database structure etc, so I presume it could take some weeks to get done.

**Comment by xet7** [comment]
Another UI design draft. Not all screens here yet.

Improvements welcome.

## Admin Panel / People

```
People [______] Search    Selected: UsernameHere

Organizations | Username Fullname Admin Email Authentication Method
Teams         | (abow column names should keep their place, not move)
People >      | (not all profile data columns listed, more at profile page) 
Profile       | (when clicking user row, it becomes selected above) 
Boards        |
```

## Admin Panel / People / Profile

```
Selected: UsernameHere
                                          _______________
Organizations | Username ...              | Avatar image |
Teams         | Fullname ...              |              |
People        | Admin    ...              |______________|
Profile >     | Email    ..
Boards        | Authentication Method
              | [Save]                      [Delete User]
              |                       (confirm, and if no boards)
```

## Admin Panel / People / Boards

```
Selected: UsernameHere

Organizations | Selected: Change to [Admin/User/.. dropdown] [Change]
Teams         |           Move to __username__ with [Admin/User/.. dropdown] [Move]
People        |           [View one board]
Profile       | 
Boards  >     | Select all - Unselect All
              | [_] BoardName 1 | Admin            
              | [_] BoardName 2 | User
              | [_] BoardName 3 | NoComments
              | [_] BoardName 4 | CommentOnly
```

**Comment by rterwedo** [comment]
making progress @xet7 !

**Comment by xet7** [comment]
Moved to here from #2744

From @Mystikal57 

Feature Request: Multiple domain for ldap authentication

Hi,

It's possible to do a multiple domain authentication possibility ?

Thank you

From @xet7 

Please describe what does it mean?

If you mean this In Progress Teams/Organizations feature, I would guess that for example it could mean:

1) At Organization settings, select domain for organization. For example:

Organization name | Domain
------------------------- | -----------
Big Company | bigcompany.com
Interesting Company | interestingcompany.com

2) At Teams, select LDAP group for each team.

Team name | LDAP Group
--------------- | -------------------
Prod Team | Prod
Designer Team | Design

There have also been some discussions with one of my customers about adding SAML to Wekan, but that customer has not made final decision about paying for that feature yet.

Also if anyone else would like to add comment, is this a general way to have multiple domain support? Or does this mean something else?

**Comment by mikesutton** [comment]
I can see this being useful for a multi tenant use -
My team doesn't really have the need for the organisational separations beyond boards and which of the users on the system can participate on which boards.

I do wonder though..if you self host Wekan, wouldn't you just install one per organisation/team  - especially with Docker it is very easy.

That would give everyone their own URL and the necessary separation too.

**Comment by justinr1234** [comment]
@mikesutton different use cases. Currently trello does not behave that way, it is 1 big platform. This is similar to how most "social" sites operate, such as Facebook. There isn't <companyname>.facebook.com --- there is a Group (organization) feature in Facebook. Users are not physically separated in the database, it's all one user base.

**Comment by mikesutton** [comment]
@justinr1234 confused about Trello - I thought it did have teams and organisations (albeit you have to subscribe).

As I see it - already wekan lets a group of people work on one or more boards in a single instance. 
Without doing anything else one could support the installing of a new instance per organisation (that gives them wekan.org.com and org wide LDAP) or a new instance per team wekan.org.com/team and a team-wide LDAP.

Or have I gone completely off the ranch into the dunes?

**Comment by mikesutton** [comment]
Wekan has a context that is fundamentally different to Trello - it's closest comparison.

It is self hosted and I think that provides benefits.

**Comment by justinr1234** [comment]
The idea is to not have the infrastructural complexity of hosting multiple instances. This becomes more cumbersome as you have to develop an infrastructure for managing, creating, and fixing issues. It's more complex than allowing segregation inside Wekan itself.

The idea would be that you don't have a physical segregation of the data between the UI. Everything would live in the same UI.

**Comment by xet7** [comment]
@mikesutton 

Teams/Organizations is for those that have for example multiple LDAP groups for different sub-organizations and teams. With scalable Wekan+MongoDB setup it is too much overhead to setup multiple installs of Wekan, it just consumes extra RAM etc. Having them in same database makes managing much easier, there is no need to add more docker containers to add a new organization or team. It also makes possible to change person to another team and organization.

Anyway, this feature already has bounty and I'm in progress of implementing this.

**Comment by xet7** [comment]
Also Templates feature will sometime have template for creating complete new organization structures etc.

**Comment by mikesutton** [comment]
@xet7 Fair enough. Will it add bloat for those that do not need that functionality or is it like a plugin type feature?

**Comment by xet7** [comment]
@mikesutton 

Wekan does not have plugins, it's all integrated, all Wekan platforms at same source code repo, with a lot of settings for turning some features on or off with environment variables. Teams/Organizations feature does not affect most small users, they just have one organization and one team. Code related to this feature is minimal, when comparing Wekan to some other more massive bloated alternatives.

**Comment by mikesutton** [comment]
@xet7 great to know, look forward to seeing this feature evolve.

**Comment by sumeet1489** [comment]
Hey @xet7 
This Team/Organization feature would be very useful. We are a conglomerate company. I look forward to have this feature in the coming releases.

**Comment by TheMasterFX** [comment]
+1 would be very nice since I want to use Wekan in my company with many teams and many departments without having to host many instances of Wekan

**Comment by derbolle** [comment]
Hello there,
is there any (very rough) estimate on when this feature will become available? 
I think a centralised Administration via Teams is one of the most important features wekan lacks at the moment

**Comment by xet7** [comment]
@derbolle 

This feature will become with these steps:
1. Ability to add users in Admin Panel.
2. New menus in Admin Panel like described here https://github.com/wekan/wekan/issues/802#issuecomment-532300344
3. Making those new menus work, affecting other parts of Wekan.
4. Ability to make Organization and Team level changes and permissions.

I really am not good in predicting exact time development takes. For previous features I have done, it has been between some days to 6 months. I hope to get done this year as many of those urgent features at [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license) as possible. In general, I will do all of those features anyway.

**Comment by xet7** [comment]
It seems someone added more to bounty, so I had to create new category `TOP PRIORITY` to [Roadmap](https://boards.wekan.team/b/D2SzJKZDS4Z48yeQH/wekan-open-source-kanban-board-with-mit-license).

**Comment by xet7** [comment]
Hi Teams/Organizations feature users,
please comment how tree menu nested tabs should work: https://github.com/wekan/wekan/issues/2796#issuecomment-590298331

**Comment by tareko** [comment]
Hello all. Is there progress on this issue? I can't figure out where to track it at this point.

**Comment by NicoP-S** [comment]
I got errors in the new org/team pages. 
`Exception in template helper: orgList...`
Is this normal because the feature is still in progess like #3420 ?

**Comment by jrsupplee** [comment]
@xet7 

I looked at some of the code for teams/orgs and I realize that this is a work in progress.  One suggestion to make determining user permissions without making many queries is to store team and org membership in the `Users` collection.  That way team and org membership for the user is available without doing further queries.

**Comment by xet7** [comment]
@jrsupplee 

Yes, this is work in progress. Thanks for suggestion!

**Comment by mweiss237** [comment]
Do you also consider the possibilty to mention a team or organization in comments with the @ character? 
That would be a huge benefit in my use case and I'm pretty sure for most other users too.

Thanks a lot for your work!

**Comment by xet7** [comment]
@mweiss237 

Well, now that you mention it, probably Yes. That mention could send message to Wekan feature `Notification drawer like Trello`.

**Comment by jrsupplee** [comment]
If `@` could be used for an org, team, or user.  The system will have to ensure that they are unique (i.e. no `username` the same as a team `name`

**Comment by xet7** [comment]
Moved to here from #3582 

From @l0ccitan3 

Hello,

in larger environments its useful, to have a function to group some user. So you would no longer need to assign users individually to a board. I have not found a function to this effect. Optionally, a mapping of the LDAP OU would also be useful.

Best Regards

**Comment by Emile840** [comment]
Hello,

As shown in the gif image below, I just fixed the bug of adding an organization, I haven't done yet a pull request for this change because I'm still working on updating and deleting an organization and a team. But before continuing, I would like to ask you a few questions to see if I have correctly understood the Team and Organization aspects, below are my questions:
- A team contains several users (a user can be found in several teams)?
- An organization contains several teams (a team can be found in several organizations)?
- If I understood correctly, there is not yet an interface to assign authenticated users to a team or to assign a team to an organization?
- If my understanding is correct, two collections are missing in the database, one to store the users assigned to teams and another to store the teams assigned to organizations?

Adding an organization is fixed:
![AddOrg](https://user-images.githubusercontent.com/83423044/120801579-9e0b0300-c541-11eb-8264-01fc45583ed5.gif)

**Comment by xet7** [comment]
@Emile840 

> 1) A team contains several users (a user can be found in several teams)?
> 2)  An organization contains several teams (a team can be found in several organizations)?

Some alternatives:

a) Previously at https://github.com/wekan/wekan/issues/802#issuecomment-757854430 @jrsupplee suggested that `users` table should have additional columns like `org` and `team`, both of them would have list of organizations etc that user belogs to, they would work like members https://github.com/wekan/wekan/blob/master/models/boards.js#L160-L180 . This way, when making database query for user, one query would include also details about organizations and teams, and there would be no need for additional queries.

b) Another, but not so good, alternative would be to try to keep similar database structure like Trello, but Trello database structure naming is kind of confusing. Currently it's kind of this:

- Wekan Organization = Trello Enterprise
- Wekan Team = [Trello Organization](https://developer.atlassian.com/cloud/trello/rest/api-group-organizations/#api-organizations-post)

c) There is also existing https://github.com/wekan/wekan/blob/master/models/orgUser.js but I think it's not so simple like a)

d) At some OAuth2/LDAP/SAML identity providers there could be some kind of organization structure mapping, I don't know would those affect some way what database structure would make most sense also in Wekan. For example, at OAuth2 Auth0 login there is some mapping of fields to Wekan fields https://github.com/wekan/wekan/wiki/OAuth2#auth0

> 3)  If I understood correctly, there is not yet an interface to assign authenticated users to a team or to assign a team to an organization?

That's correct, I would presume that would be done in `Admin Panel / People / People` but if there are some better suggestions I'm all ears.

> 4) If my understanding is correct, two collections are missing in the database, one to store the users assigned to teams and another to store the teams assigned to organizations?

Yes, if for database structure this would be selected https://github.com/wekan/wekan/blob/master/models/orgUser.js

In general, you can add these with whatever way seems to make most sense for you. You can look at existing Wekan UI components and use similar code they have.

Yes, all community help with pull requests is very welcome and speeds up progress, I have a very  long todo list with Wekan features, fixes, maintenance etc.

**Comment by xet7** [comment]
Alternatively:

e) `org` table, add column `teams` (similar to `members`) where would be possible to add those teams that belong to organization. And, `team` table, add column `users` (similar to `members`) where would be possible to add those `userId`s that belong to organization. That would maybe be more easily editable, than adding even more to `Admin Panel / People / People`.

**Comment by xet7** [comment]
@Emile840 

Please send your current code, where saving Organizations and Teams works, as pull request. It is much easier to review and merge small pull requests, than one big pull request. It is already much better because saving works.

**Comment by Emile840** [comment]
I think that before deleting an organization or team, we have to make sure that there isn't any user who belongs to it, right ?

**Comment by xet7** [comment]
@Emile840 

No, it's not necessary:
- If Organization does not exist, Organization name is not shown
- If deleted Organization is added back with same name, it becomes visible again, with same members. It's like undo.

**Comment by Emile840** [comment]
But in user collection ('orgs' column) we will still had deleted organization ?

**Comment by xet7** [comment]
@Emile840 

Well, maybe there should be some way to remove user from organization. I think you are right.

What is remaining from this Teams/Organization feature, is:

1) Add to database boards collection, also similar org and team columns like at Users table

2) Add to All Board page Tabs like these:
- https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebarArchives.jade#L3
- https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebarArchives.js

There could be tabs like:
```
My Boards | Organization name 1 | Organization name 2
```
When clicking Organization name 1, it would show below subtab 
```
Organization name 1 boards | Team name 1 boards | Team name 2 boards
```

3) At board Sidebar, above Members, add Organizations and Teams:
```
Organizations
[+]

Teams
[+]

Members
[+]
```
When some Organization or Team is added to board, board is visible to all of their members. It is not necessary to add members separately.

If someone has better ideas to this, it's all welcome.

**Comment by Emile840** [comment]
> @Emile840
> 
> Well, maybe there should be some way to remove user from organization. I think you are right.
> 
> What is remaining from this Teams/Organization feature, is:
> 
> 1. Add to database boards collection, also similar org and team columns like at Users table
> 2. Add to All Boards page Tabs like these:
> 
> * https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebarArchives.jade#L3
> * https://github.com/wekan/wekan/blob/master/client/components/sidebar/sidebarArchives.js
> 
> There could be tabs like these, for showing boards of organizations and teams:
> 
> ```
> My Boards | Organization name 1 | Organization name 2 | Team name 1 | Team name 2
> ```
> 
> And when some tab is shows, below is boards that belong to it.
> 
> 1. At board Sidebar, above Members, add Organizations and Teams:
> 
> ```
> Organizations
> [+]
> 
> Teams
> [+]
> 
> Members
> [+]
> ```
> 
> When some Organization or Team is added to board, board is visible to all of their members. It is not necessary to add members separately.
> 
> If someone has better ideas to this, it's all welcome.


Is there any one who can help me with this below issue: 

I modified boards collection to add org and team columns (similar to what i did to Users collection). i'm working on adding teams and organizations at board Sidebar, above Members (see image below)
![image](https://user-images.githubusercontent.com/83423044/123830516-a87fa900-d903-11eb-8b26-f84a90a7fc88.png)

When user clik that + button (see above image), i want to display a pop-up with dropdown list to choose an organization, but i have a problem of getting organization list from database. I'm trying to do that by using Org object in sidebar.js file (see image below) but it gives me an error : "Method 'org' not found [404]\n at Connection._livedata_result ..." 

![image](https://user-images.githubusercontent.com/83423044/123833153-5ab87000-d906-11eb-8a78-fbc04702418f.png)

**Comment by xet7** [comment]
@Emile840 

You can add user table/collection fields `org` and `team` to users publication, that is published from serverside, so that user can add those organizations and teams that user is member of:
https://github.com/wekan/wekan/blob/master/server/publications/users.js

Then similarly, like showing `org` at Admin Panel, subscribe to [user-miniprofile](https://github.com/wekan/wekan/blob/master/server/publications/users.js) publication at `sidebar.js` to above `orgsDatas()` in your `Template.addBoardOrgPopup.helpers` :
https://github.com/wekan/wekan/blob/master/client/components/settings/peopleBody.js#L31

But you should not modify this `org` publication, because only Admin can see all organizations:
https://github.com/wekan/wekan/blob/master/server/publications/org.js#L10

**Comment by xet7** [comment]
Maybe this is better example of subscribing:
https://github.com/wekan/wekan/blob/master/client/components/main/header.js#L3
```
Meteor.subscribe('user-miniprofile');
```

**Comment by Emile840** [comment]
> @Emile840
> 
> You can add user table/collection fields `org` and `team` to users publication, that is published from serverside, so that user can add those organizations and teams that user is member of:
> https://github.com/wekan/wekan/blob/master/server/publications/users.js
> 
> Then similarly, like showing `org` at Admin Panel, subscribe to [user-miniprofile](https://github.com/wekan/wekan/blob/master/server/publications/users.js) publication at `sidebar.js` to above `orgsDatas()` in your `Template.addBoardOrgPopup.helpers` :
> https://github.com/wekan/wekan/blob/master/client/components/settings/peopleBody.js#L31
> 
> But you should not modify this `org` publication, because only Admin can see all organizations:
> https://github.com/wekan/wekan/blob/master/server/publications/org.js#L10

Thanks @xet7, i used Meteor.subscribe similarly to what was done to Admin Panel and it's working.

**Comment by adelphi-company** [comment]
As I don't see it on your task list: Do you plan to create Wekan Teams out of LDAP Groups? That would be quite useful for LDAP environments.

**Comment by xet7** [comment]
@adelphi-company 

From AD groups yes, but I have not yet looked at AD code. LDAP could be using same or different way to list groups.

Any help like code examples would be very welcome, how to list groups of AD, LDAP, SAML etc. WeKan LDAP etc code is at ’wekan/packages/'

Also coming is adding some domain members automatically to some team or organization when user of that domain logins.

Hmm, maybe also limiting logins only to allowed domain on Standalone WeKan. Currenly only Sandstorm WeKan has that feature that is actually Sandstorm Admin Panel feature, not WeKan feature.

**Comment by adelphi-company** [comment]
> From AD groups yes, but I have not yet looked at AD code. LDAP could be using same or different way to list groups.
> Any help like code examples would be very welcome, how to list groups of AD, LDAP, SAML etc. WeKan LDAP etc code is at wekan/packages/

We are using AD and all our other (>10) web tools with LDAP integration are able to read groups and groups memberships easily, even nested ones. So I assume there is no big difference.

IMHO it's pretty similar to getting users but instead of querying (objectClass=user) you query for (objectclass=group) in a given SearchBase (see https://ldapwiki.com/wiki/Active%20Directory%20Group%20Related%20Searches). Search base can be different to the one for users, so its alsways useful to offer seperate settings . You can apply similar LDAP filters and in the end you get a list of all groups that need to be created as Wekan Teams.

Also, if you query for (objectClass=user), you can use attribute "memberOf" to see which groups are assigned to a user and make him member of the appropriate Wekan Team(s).

Nested groups are detected via "1.2.840.113556.1.4.1941" in a "memberOf" query, e.g.
(memberOf:1.2.840.113556.1.4.1941:=CN=Admins,OU=Groups,OU=Ressources,DC=domain,DC=de)

If you need some suggestions:
A very good (and more advanced) LDAP group implementation can be found in the Nextcloud docs, : https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html
Other good LDAP implementations with groups:
TeamPasswordManager: https://teampasswordmanager.com/docs/ldap-sync/#ldap_groups
CheckMK: https://docs.checkmk.com/latest/en/ldap.html
Moodle: https://docs.moodle.org/310/en/LDAP_authentication#Assign_system_roles

> Also coming is adding some domain members automatically to some team or organization when user of that domain logins.

Great. This would be very useful too.

> Hmm, maybe also limiting logins only to allowed domains

For us not important and I think with appropriate LDAP filter attributes this can be achieved already, or not?
